/* eslint-disable no-restricted-globals */
// Workbox-powered service worker for CRA.
// This file is used in production builds only (workbox injects the precache manifest).

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkOnly, StaleWhileRevalidate } from 'workbox-strategies';

clientsClaim();

// Auth endpoints: never cache (login, refresh, logout). Avoid stale auth responses in PWA.
const authPaths = ['/api/user/login', '/api/user/registration', '/api/user/google', '/api/user/refresh', '/api/user/logout'];
registerRoute(
  ({ url }) => authPaths.some((p) => url.pathname.endsWith(p)),
  new NetworkOnly()
);

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below by Workbox.
precacheAndRoute(self.__WB_MANIFEST);

// App-shell style routing: return index.html for navigation requests.
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  ({ request, url }) => {
    if (request.mode !== 'navigate') return false;
    if (url.pathname.startsWith('/_')) return false;
    if (url.pathname.match(fileExtensionRegexp)) return false;
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// Cache images with a stale-while-revalidate strategy.
registerRoute(
  ({ request }) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [new ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 })],
  })
);

// Allow clients to trigger skipWaiting via postMessage.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});


