/* eslint-disable no-restricted-globals */
// Workbox-powered service worker for CRA.
// This file is used in production builds only (workbox injects the precache manifest).

import { clientsClaim } from 'workbox-core';
import { CacheFirst, NetworkOnly, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';

clientsClaim();

// -------------------------------------------------------------------
// API and Auth routes: NEVER cache (always fetch from network)
// Covers: /api/*, /auth/*, and any auth-related endpoints
// -------------------------------------------------------------------
registerRoute(
  ({ url }) => {
    const path = url.pathname;
    // Never cache API routes
    if (path.startsWith('/api/') || path.startsWith('/api')) return true;
    // Never cache auth routes
    if (path.startsWith('/auth/') || path.startsWith('/auth')) return true;
    // Never cache workspace API routes
    if (path.startsWith('/workspace/') && path.includes('/desk/')) return true;
    return false;
  },
  new NetworkOnly()
);

// -------------------------------------------------------------------
// Supabase Storage (CDN): Cache aggressively
// Files are immutable (unique filenames with timestamps)
// -------------------------------------------------------------------
registerRoute(
  ({ url }) => {
    // Match Supabase storage URLs (*.supabase.co/storage/*)
    return url.hostname.endsWith('.supabase.co') && url.pathname.includes('/storage/');
  },
  new CacheFirst({
    cacheName: 'supabase-storage',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year (files are immutable)
      }),
    ],
  })
);

// -------------------------------------------------------------------
// Precache build assets
// -------------------------------------------------------------------
// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below by Workbox.
precacheAndRoute(self.__WB_MANIFEST);

// -------------------------------------------------------------------
// App-shell style routing
// -------------------------------------------------------------------
// Return index.html for navigation requests (SPA routing).
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  ({ request, url }) => {
    if (request.mode !== 'navigate') return false;
    if (url.pathname.startsWith('/_')) return false;
    if (url.pathname.match(fileExtensionRegexp)) return false;
    // Don't serve index.html for API routes
    if (url.pathname.startsWith('/api/')) return false;
    if (url.pathname.startsWith('/auth/')) return false;
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// -------------------------------------------------------------------
// Image caching (non-Supabase images)
// -------------------------------------------------------------------
registerRoute(
  ({ request, url }) => {
    // Skip Supabase images (handled above with CacheFirst)
    if (url.hostname.endsWith('.supabase.co')) return false;
    return request.destination === 'image';
  },
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [new ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 })],
  })
);

// -------------------------------------------------------------------
// Skip waiting on message
// -------------------------------------------------------------------
// Allow clients to trigger skipWaiting via postMessage.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});


